### ISSUE TITLE
support for icon-fonts

### ISSUE THREAD

**Issue by juanbrujo** [Munter/subfont#1]
It should be great to support icon-fonts like fontawesome, so used and not optimized at all

**Comment by Munter** [comment]
I totally agree. The methods I am using can actually be made completely generic, so all local fonts could be optimized as well. The only thing I need is a reliable and available toolset for creating the actual font subset from the original font and the known glyphs. The problem I'm facing is that no such tool exists in the node ecosystem, so I'd have to force users to install external dependencies.

I'm interested in giving out how Google does their subsetting, since that seems to work well. I'd like to have a similar simple implementation

**Comment by Munter** [comment]
Released in subfont v2.0.0: https://www.npmjs.com/package/subfont
