### ISSUE TITLE
Html auto-closing tags are being replaced with 'classic' tag syntax

### ISSUE THREAD

**Issue by dotlouis** [Munter/subfont#38]
When running subfont on my HTML file all my auto-closing tags are being rewritten to "classic" tags.

For example
`<input type="text" />` becomes `<input type="text">`
or `<img src="..." />` becomes `<img src="...">`

That's not blocking because it's still valid HTML but why would it rewrite the tags?
When running the diff between the generated HTML and the original to see the changes, it creates unnecessary noise.

**Comment by Munter** [comment]
Subfont is using [Assetgraph](https://github.com/assetgraph/assetgraph) to model html assets. It uses jsdom to parse the html and create a DOM, which it the manipulates to inject the right preload hints, stylesheets and scripts. Since we made DOM modifications that tree needs to be serialised again for writing to disk. I assume this is JSDOM's serialization process that removes the auto-closing

**Comment by dotlouis** [comment]
Okay, thanks for the clarification. I've posted my question here: https://github.com/jsdom/jsdom/issues/2302

**Comment by papandreou** [comment]
We can't easily do that as that information doesn't survive a round-trip through JSDOM.

However, why do you want to use `/>`? It's an XHTML-ism, HTML doesn't actually support it, it's just being tolerated by the HTML5 parsing algorithm.

**Comment by dotlouis** [comment]
I did not know it was not valid HTML. Always thought this was the other way around. `/>` being the correct standard way and `>` the tolerated way. Will change that behavior ASAP. Also a few more bytes saved ;)
